version: '2'

services:
  restapi:
    image: 'managestore:latest'
    build:
      context: ""
      dockerfile: Dockerfile
    container_name: rest_api_container
    ports:
      - "9090:9090"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ManageStoreTest
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456789
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: ManageStoreTest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5432:5432"
