server:
  port: 9090
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ManageStoreV1
    username: postgres
    password: 123456789
  jpa:
    show-sql: true
  #liquibase Config
  liquibase:
    change-log: db/master.xml
    enabled: true
  test:
    database:
      replace: none